apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-api-user
        image: docker.io/solomanm/udagram-api-user:v1
        env:
          - name: POSTGRES_USERNAME
            value: "database1"
          - name: POSTGRES_PASSWORD
            value: "Database1"
          - name: POSTGRES_HOST
            value: "database1.c1jqzsr8uemu.us-east-1.rds.amazonaws.com"
          - name : POSTGRES_DB
            value: "postgres"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
          requests: 
            cpu: "200m"
          

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  selector:
    app: backend-user
